### PR TITLE
Check if a dispatcher actually exists before setting its targets

### PR DESCRIPTION
**Pull request by boboldehampsink**
Fixes errors like `[Error] Attempt to modify property "targets" on null `

### CODE REVIEW

**Comment by engram-design** [comment]
Thanks! I assume this is when you have no disk logging enabled like on Heroku?

FYI @bencroker

**Comment by boboldehampsink** [comment]
@engram-design this actually happens when running tests with Craft

**Comment by engram-design** [comment]
Ah, I see. I can vaguely recall the same issue (not marked here on this repo) you raised back in Craft 3 days for this reason. Thanks again

**Comment by boboldehampsink** [comment]
You're right!

**Comment by bencroker** [comment]
How are you running tests @boboldehampsink? Craft's testing framework should include a default logger, in which case this is not an issue.

**Comment by bencroker** [comment]
Ah ok, I see that this is an issue for modules that are auto bootstrapped. I ended up applying this fix in https://github.com/putyourlightson/craft-sprig-core/commit/9dfc817fb7637915b761187f8702fc271e91d0f1 too, thanks @boboldehampsink!

**Comment by boboldehampsink** [comment]
Yw @bencroker! @engram-design any chance of releasing 2.0.1 soon?

**Comment by engram-design** [comment]
Sorry @boboldehampsink at Dot All in Brooklyn, but can tag this shortly

**Pull request merged**
